apiVersion: apps/v1
kind: Deployment
metadata:
  name: AuthenticationMicroservice
  labels:
    app: AuthenticationMicroservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuthenticationMicroservice  
  template:
    metadata:
      labels:
        app: AuthenticationMicroservice
    spec:
      containers:
      - name: AuthenticationMicroservice
        image: mycontainerregistry022022.azurecr.io/authenticationapi:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: myacrcredentails
---
apiVersion: v1
kind: Service
metadata:
  name: AuthenticationMicroservicesvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AuthenticationMicroservice